FROM alpine:latest

COPY --chown=root:root server/ssh /etc/ssh/
COPY --chown=root:root server/script /opt/sshnet
COPY --chown=sshnet:sshnet user/sshnet /home/sshnet/.ssh

RUN apk add --no-cache syslog-ng && \
    # install and configure sshd
    apk add --no-cache openssh && \
    # install openssh-server-pam to allow for keyboard-interactive authentication
    apk add --no-cache openssh-server-pam && \
    chmod 400 /etc/ssh/ssh*key && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's/#LogLevel\s*INFO/LogLevel DEBUG3/' /etc/ssh/sshd_config && \
    echo 'PubkeyAcceptedAlgorithms ssh-rsa' >> /etc/ssh/sshd_config && \
    chmod 646 /etc/ssh/sshd_config && \
    # install and configure sudo
    apk add --no-cache sudo && \
    addgroup sudo && \
    sed -i 's/#\s*%sudo\s*ALL=(ALL)\s*ALL/%sudo ALL=(ALL) NOPASSWD:ALL/' /etc/sudoers && \
    # add user to run most of the integration tests
    adduser -D sshnet && \
    passwd -u sshnet && \
    echo 'sshnet:ssh4ever' | chpasswd && \
    dos2unix /home/sshnet/.ssh/* && \
    chown -R sshnet:sshnet /home/sshnet && \
    chmod -R 700 /home/sshnet/.ssh && \
    chmod -R 644 /home/sshnet/.ssh/authorized_keys && \
    # add user to administer container (update configs, restart sshd)
    adduser -D sshnetadm && \
    passwd -u sshnetadm && \
    echo 'sshnetadm:ssh4ever' | chpasswd && \
    addgroup sshnetadm sudo && \
    dos2unix /opt/sshnet/* && \
    # install shadow package; we use chage command in this package to expire/unexpire password of the sshnet user
    apk add --no-cache shadow

EXPOSE 22 22

ENTRYPOINT ["/opt/sshnet/start.sh"]